version: '3'
services:
  emqx:
    image: emqx/emqx:5.8.3
    container_name: emqx
    restart: always
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8084:8084"
      - "8883:8883"
      - "18083:18083"
    volumes:
      - /deploy/emqx/data:/opt/emqx/data
      - /deploy/emqx/log:/opt/emqx/log
      - /deploy/emqx/etc:/opt/emqx/etc  
      - /deploy/emqx/certs:/opt/emqx/certs
    environment:
      - EMQX_ALLOW_ANONYMOUS=false
