version: '3'
services:
  emqx:
    image: emqx/emqx:5.8.3
    container_name: emqx
    restart: always
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8084:8084"
      - "8883:8883"
      - "18083:18083"
    volumes:
      - $PWD/data:/opt/emqx/data
      - $PWD/log:/opt/emqx/log
      - $PWD/etc:/opt/emqx/etc  
      - $PWD/certs:/opt/emqx/certs
    environment:
      - EMQX_ALLOW_ANONYMOUS=false
